[project]
name = "python-exercices"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dataclasses>=0.8",
    "datetime>=5.5",
    "ruff>=0.11.13",
    "typing>=3.10.0.0",
]
